services:
  chekingaccount.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DbConnection=Data Source=checkingaccountdb
      - Jwt__Secret=fd4578204b39eb6f3ad771578e5acdd657104b659d73c389f3431a727c906ddf
      - Jwt__Issuer=http://chekingaccount.api:8080
      - Jwt__Audience=http://chekingaccount.api:8080
      - Jwt__ExpirationInMinutes=15
    ports:
      - "6060:8080"
      - "6000:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  transfer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DbConnection=Data Source=transferdb
      - Jwt__Secret=fd4578204b39eb6f3ad771578e5acdd657104b659d73c389f3431a727c906ddf
      - Jwt__Issuer=http://chekingaccount.api:8080
      - Jwt__Audience=http://chekingaccount.api:8080
      - ChekingAccountApi__BaseUri=http://chekingaccount.api:8080
    ports:
      - "6061:8080"
      - "6001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
